### ISSUE TITLE
Effect words - prio 2

### ISSUE THREAD

**Issue by Ulleren** [Greve2001/02148_G8#70]
Make so that effects can happen. Start with a single effect word, slow down your words speed.

**Comment by Greve2001** [comment]
Potential Features:

- [ ] Decrease own words falling speed by 2s for 10s
- [ ] Increase opponent words falling speed by -2s for 10s
- [ ] Send two character words to opponent (Should naturally be very fast falling)
- [ ] Make opponent words invisible for 1s
